version: "3.6"

services:
  identity.api:
    container_name: ads.identity
    image: ads.identity
    build:
      context: .
      dockerfile: src/Ookbee.Ads.Services.Identity/Dockerfile
    networks:
      - loc
    ports:
      - "5010:5010"
    environment:
      - ASPNETCORE_ENVIRONMENT=Local
      - ASPNETCORE_URLS=http://+:5010

  manager.api:
    container_name: ads.manager
    image: ads.manager
    build:
      context: .
      dockerfile: src/Ookbee.Ads.Services.Management/Dockerfile
    networks:
      - loc
    ports:
      - "5020:5020"
    environment:
      - ASPNETCORE_ENVIRONMENT=Local
      - ASPNETCORE_URLS=http://+:5020

  analytics.api:
    container_name: ads.analytics
    image: ads.analytics
    build:
      context: .
      dockerfile: src/Ookbee.Ads.Services.Analytics/Dockerfile
    networks:
      - loc
    ports:
      - "5030:5030"
    environment:
      - ASPNETCORE_ENVIRONMENT=Local
      - ASPNETCORE_URLS=http://+:5030

  publish.api:
    container_name: ads.publish
    image: ads.publish
    build:
      context: .
      dockerfile: src/Ookbee.Ads.Services.Publish/Dockerfile
    networks:
      - loc
    ports:
      - "5040:5040"
    environment:
      - ASPNETCORE_ENVIRONMENT=Local
      - ASPNETCORE_URLS=http://+:5040

networks:
  loc:
    name: loc-network
    external: true
