@apiUrl = http://localhost:5000/api
@accessToken = QEAQAAABAAAABWNIAO4TISY3JWRGE2YSK2EKEW53AU2V4AAAAAANWAL3EJJGKZTSMVZWQVDPNNSW4SLEEI5CENDDMQ3DKMRSMYWWCMJVHEWTINZXMMWWEOBZMQWWGOLCMI3DOYTGGRSWGYJCFQRES42BMRWWS3TJON2HEYLUN5ZCEOTGMFWHGZJMEJHW623CMVSU45LNMVZGSY2JMQRDUNRTHAZTKMJRFQREC4DQINXWIZJCHIRECTSOIFPTOMBZEIWCEVDPNNSW4S3JNZSCEORCMFRWGZLTON2G623FNYRCYISEMV3GSY3FJFSCEORCO5SWE43JORSS6YLONZQS2ZDFOYXG633LMJSWKLTOMV2DUNJWGM2CELBCIV4HI4TBIFYHAQ3PMRSXGIR2LNOX2ZHRSGVFMHNWHKQZTB464AE66JB7GZPZNWHIE65H3GO6LCKLWAC7CGWRQOFEPWTQM
@accessTokenExpired = QEAQAAABAAAAAMWQNZMPRD2KIOV7WZFVNBPWCWHQMIZF4AAAAAANWAL3EJJGKZTSMVZWQVDPNNSW4SLEEI5CEYJQG5RTCMZQGEWWIYRUGEWTIM3GMEWWCNRWG4WTMZRYG4YDMNBZGYYTMOJCFQRES42BMRWWS3TJON2HEYLUN5ZCEOTGMFWHGZJMEJHW623CMVSU45LNMVZGSY2JMQRDUNRTHAZTKMJRFQREC4DQINXWIZJCHIRECTSOIFPTOMBZEIWCEVDPNNSW4S3JNZSCEORCMFRWGZLTON2G623FNYRCYISEMV3GSY3FJFSCEORCO5SWE43JORSS6YLONZQS2ZDFOYXG633LMJSWKLTOMV2DUNJWGM2CELBCIV4HI4TBIFYHAQ3PMRSXGIR2LNOX2DGMUV4PSOLGAX6TWZHOGM5V7UGAGRLWTL5PTFWYXQRLEJWSH46VK5KNCNWU4TFAE
@userId = 6383511

### Utility *******************************

### HealthChecks
GET {{apiUrl}}/health
content-type: application/json

### Campaign *******************************

### Get comment list
GET {{apiUrl}}/campaigns?start=0&length=10
content-type: application/json
Authorization: Bearer {{accessToken}}